# Generated by Django 2.2.1 on 2019-05-20 15:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shortener_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortening',
            old_name='url',
            new_name='long_url',
        ),
    ]
