# Generated by Django 2.2.1 on 2019-05-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shortener_app', '0002_auto_20190520_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortening',
            name='short_url',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
