# Generated by Django 2.2.1 on 2019-05-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shortener_app', '0003_shortening_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortening',
            name='short_url',
            field=models.CharField(max_length=55),
        ),
    ]
